server:
  port: 8080

spring:
  application:
    name: ncbot
  datasource:
    url: jdbc:sqlite:ncbot.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
  ai:
    openai:
      api-key: ${NCBOT_API_KEY:default-key}
      base-url: ${NCBOT_OPENAI_BASE_URL:http://192.168.1.240:11435/v1}
      chat:
        options:
          model: ${NCBOT_MODEL:ncbot}

ncbot:
  system-prompt: |
    You are ncbot, an AI assistant on the Meshcore mesh network.
    You are tasked to respond to the user message in a short and concise way.
    Your entire response should be no more than 128 UTF-8 bytes in length.
    Use emojis to save bytes.
    Tag users as @[username] (e.g. @[nc1v])
    Do not prefix your response with your name.
    Use the available tools to help you.
    Use the provided conversation memory and latest messages to help you respond as a participant in the conversation.
  condense-prompt: |
    Condense the following response to ≤128 UTF-8 bytes.
    Preserve meaning; cut filler.
    Response should only be the shorted response with nothing else.
  memory-prompt: |
    Your task is to summarize the provided conversation history.
    The summary that is produced will be used by ncbot as its long term memory.
  combine-prompt: |
    You are an expert at combining historical conversation memory with new information.
    You will be provided the historical conversation memory followed by a summary of new information.
    Your response should be an updated conversation memory that contains important information from both.
    You can assume the new information comes after the historical memory.
    The only time you should omit information is when it is no longer relevant or has been superseded by later information.
    You may return the historical conversation memory when nothing should be changed.
  memory-update-cron: ${NCBOT_MEMORY_UPDATE_CRON:3 0 * * *}
  minimum-response-ms: ${NCBOT_MINIMUM_RESPONSE_MS:0}
  max-reply-bytes: ${NCBOT_MAX_REPLY_BYTES:128}
  allowed-channels:
    - "#ncbot"
  allow-dms: true

gg:
  jte:
    development-mode: ${JTE_DEV_MODE:false}
    use-precompiled-templates: true

logging:
  level:
    root: WARN
    org.huebert: DEBUG
