/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all channels
         * @description Returns a paginated list of all known chat channels. Optionally filter to DMs or non-DM channels,
         *     and optionally search by case-insensitive substring match on channel name or key.
         *     Results are sorted by most recent message descending (channels without messages sort last),
         *     then alphabetically by `channelName`.
         */
        get: operations["listChannels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/channels/{channelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a channel
         * @description Permanently deletes a channel and all associated messages and channel-scoped memories.
         *     The channel must exist; returns 400 if not found.
         */
        delete: operations["deleteChannel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/channels/{channelId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List messages for a channel
         * @description Returns a paginated list of chat messages for the given channel, optionally filtered by
         *     time range and sorted in ascending or descending order.
         */
        get: operations["getChannelMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/channels/{channelId}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List channel memories
         * @description Returns a paginated list of AI-synthesized memories scoped to the given channel.
         *     Results are sorted alphabetically by `key`. An optional `query` filters by
         *     case-insensitive substring match on memory key or value.
         */
        get: operations["getChannelMemory"];
        put?: never;
        /**
         * Create a channel memory
         * @description Creates a new AI-synthesized memory scoped to the given channel.
         *     The memory is persisted immediately and returned with its assigned `id`.
         */
        post: operations["createChannelMemory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/channels/{channelId}/memory/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a channel memory
         * @description Updates the key and/or value of an existing channel-scoped memory.
         *     Validates that the memory belongs to the specified channel.
         */
        put: operations["updateChannelMemory"];
        post?: never;
        /**
         * Delete a channel memory
         * @description Permanently deletes a channel-scoped memory.
         *     Validates that the memory belongs to the specified channel before deleting.
         */
        delete: operations["deleteChannelMemory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/channels/{channelId}/memory/{id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Promote a channel memory to global
         * @description Copies a channel-scoped memory to the global memory store and deletes the original.
         *     The promoted memory is returned with a new `id` (global scope, `channelId: null`).
         */
        post: operations["promoteMemory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/channels/{channelId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List participants for a channel
         * @description Returns a paginated list of unique senders (participants) who have posted in the given channel.
         *     Results are sorted alphabetically by sender name. An optional `query` filters by
         *     case-insensitive substring match on sender name.
         */
        get: operations["getChannelParticipants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List global memories
         * @description Returns a paginated list of AI-synthesized memories with global scope
         *     (not tied to any channel). Results are sorted alphabetically by `key`.
         *     An optional `query` filters by case-insensitive substring match on memory key or value.
         */
        get: operations["getGlobalMemory"];
        put?: never;
        /**
         * Create a global memory
         * @description Creates a new AI-synthesized memory with global scope (not tied to any channel).
         *     The memory is persisted immediately and returned with its assigned `id`.
         */
        post: operations["createGlobalMemory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memory/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a global memory
         * @description Updates the key and/or value of an existing global memory.
         *     Validates that the memory has global scope (no associated channel).
         */
        put: operations["updateGlobalMemory"];
        post?: never;
        /**
         * Delete a global memory
         * @description Permanently deletes a global memory.
         *     Validates that the memory has global scope before deleting.
         */
        delete: operations["deleteGlobalMemory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all configuration items
         * @description Returns every known DB-backed configuration item with its type, current value,
         *     default value, description, and whether a change requires a restart. Items are
         *     seeded with sensible defaults on first start, so this list is always complete.
         */
        get: operations["listConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a configuration item
         * @description Validates the new value against the item's declared type and updates it in the
         *     database. Runtime items take effect immediately; items that are only read at
         *     startup are stored now but require a restart to take effect.
         */
        put: operations["updateConfig"];
        post?: never;
        /**
         * Reset a configuration item to its default
         * @description Removes the stored override so the item reverts to its seeded default value.
         */
        delete: operations["resetConfig"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all participants with last seen
         * @description Returns a paginated list of all known participants across all channels,
         *     including their last seen timestamp. Results are sorted by most recently active.
         *     An optional `query` filters by case-insensitive substring match on participant name.
         */
        get: operations["getAllParticipants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/participants/{participantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a participant (block/unblock)
         * @description Updates a participant's explicit block state. Blocked participants are ignored by the
         *     bot, in addition to any `block-user` regex matches (an `allow-user` regex still takes
         *     precedence). Returns the updated participant.
         */
        put: operations["updateParticipant"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A chat channel with its identifying key, name, and most recent activity. */
        ChannelDto: {
            /**
             * Format: int64
             * @description Unique database ID of the channel.
             * @example 1
             */
            id?: number;
            /**
             * @description The unique identifier for the channel (e.g., an IRC channel name like `#ncbot`
             *     or a hex-encoded key for DMs).
             * @example #ncbot
             */
            channelKey?: string;
            /**
             * @description Human-readable display name. May be `null` for DM channels.
             * @example #ncbot
             */
            channelName?: string | null;
            /**
             * @description Whether this channel is a direct message.
             * @example false
             */
            isDm?: boolean;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp of the most recent message in the channel, or `null` if the
             *     channel has no messages yet.
             * @example 2026-06-03T14:30:00Z
             */
            lastMessageAt?: string | null;
        };
        /** @description A single chat message with sender, timestamp, and optional bot response. */
        MessageDto: {
            /**
             * Format: int64
             * @description Unique database ID of the message.
             * @example 101
             */
            id?: number;
            /**
             * @description Name of the user who sent the message.
             * @example alice
             */
            senderName?: string;
            /**
             * @description The text content of the message.
             * @example Hello everyone!
             */
            content?: string;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp when the message was created.
             * @example 2026-06-03T14:30:00Z
             */
            createdAt?: string;
            /**
             * @description The ncbot response text generated for this message, or `null` if the bot did not respond.
             * @example @[alice] Hello! Welcome to the channel.
             */
            response?: string | null;
        };
        /**
         * @description An AI-synthesized key-value memory. `channelId` is `null` for global memories
         *     and set for channel-scoped memories.
         */
        MemoryDto: {
            /**
             * Format: int64
             * @description Unique database ID of the memory.
             * @example 42
             */
            id?: number;
            /**
             * Format: int64
             * @description ID of the channel this memory belongs to. `null` for global memories.
             * @example 1
             */
            channelId?: number | null;
            /**
             * @description Dot-namespaced key identifying the memory (e.g. `user.alice`, `channel.#ncbot`, `bot.version`).
             * @example user.alice
             */
            key?: string;
            /**
             * @description The synthesized memory value (free-form text).
             * @example Alice is a regular contributor who enjoys discussing technology.
             */
            value?: string;
        };
        /** @description A chat participant (user) with their timestamps, block state, and path upgrade notification state. */
        ParticipantDto: {
            /**
             * Format: int64
             * @description Unique database ID of the participant.
             * @example 1
             */
            id?: number;
            /**
             * @description The participant's display name.
             * @example alice
             */
            name?: string;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp of when the participant was first seen.
             * @example 2026-06-01T09:00:00Z
             */
            firstSeen?: string | null;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp of the participant's most recent activity.
             *     `null` when listing participants for a specific channel (historical senders only).
             * @example 2026-06-03T14:30:00Z
             */
            lastSeen?: string | null;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp of when the participant was last notified to upgrade their
             *     path hash, or `null` if they have never been notified.
             * @example 2026-06-02T10:00:00Z
             */
            pathUpgradeNotifiedAt?: string | null;
            /**
             * @description Whether the participant is explicitly blocked. Blocked participants are ignored by
             *     the bot unless they match an `allow-user` regex.
             * @example false
             */
            blocked?: boolean;
        };
        /** @description Request body for creating a new memory. */
        MemoryCreateRequest: {
            /**
             * @description Dot-namespaced key for the memory (e.g. `user.alice`, `bot.version`).
             * @example user.bob
             */
            key: string;
            /**
             * @description The key-value content to store.
             * @example Bob recently joined the channel and is learning the ropes.
             */
            value: string;
        };
        /** @description Request body for updating an existing memory. */
        MemoryUpdateRequest: {
            /**
             * @description Updated key for the memory.
             * @example user.bob
             */
            key: string;
            /**
             * @description Updated value for the memory.
             * @example Bob is now an active member and contributes regularly.
             */
            value: string;
        };
        /** @description Request body for updating a participant's block state. */
        ParticipantUpdateRequest: {
            /**
             * @description Whether the participant should be blocked.
             * @example true
             */
            blocked: boolean;
        };
        /** @description A DB-backed configuration item with its current value and code-defined metadata. */
        ConfigItemDto: {
            /**
             * @description Dot-namespaced configuration key (e.g. `bot.name`).
             * @example chat.max-reply-bytes
             */
            key?: string;
            /**
             * @description Logical value type, used for validation and UI rendering.
             * @example INT
             * @enum {string}
             */
            type?: "STRING" | "TEXT" | "BOOLEAN" | "INT" | "LONG" | "LIST";
            /**
             * @description Current effective value (stored value, or default if not overridden).
             * @example 128
             */
            value?: string;
            /**
             * @description The seeded default value.
             * @example 128
             */
            defaultValue?: string;
            /** @description Human-readable description shown in the admin UI. */
            description?: string;
            /**
             * @description Whether a change only takes effect after an application restart.
             * @example false
             */
            restartRequired?: boolean;
            /**
             * @description Whether the current value equals the seeded default (no override stored).
             * @example true
             */
            isDefault?: boolean;
        };
        /** @description Request body for updating a configuration item's value. */
        ConfigItemUpdateRequest: {
            /**
             * @description New raw value, validated against the item's declared type.
             * @example 256
             */
            value: string;
        };
        /** @description Paginated message list for a specific channel, including channel metadata. */
        MessagesResponse: {
            /**
             * Format: int64
             * @description ID of the channel the messages belong to.
             * @example 1
             */
            channelId?: number;
            /**
             * @description Display name of the channel.
             * @example #ncbot
             */
            channelName?: string | null;
            /** @description List of messages on this page. */
            messages?: components["schemas"]["MessageDto"][];
            /**
             * @description Total number of pages available.
             * @example 5
             */
            totalPages?: number;
            /**
             * @description Current page number (0-indexed).
             * @example 1
             */
            currentPage?: number;
            /**
             * Format: int64
             * @description Total number of messages across all pages.
             * @example 97
             */
            totalElements?: number;
        };
        /** @description Generic paginated response wrapper. The `content` field type depends on context. */
        PageResponse: {
            /** @description The items on the current page. */
            content?: unknown[];
            /**
             * @description Total number of pages.
             * @example 1
             */
            totalPages?: number;
            /**
             * @description Current page number (0-indexed).
             * @example 1
             */
            currentPage?: number;
            /**
             * Format: int64
             * @description Total number of items across all pages.
             * @example 3
             */
            totalElements?: number;
        };
        PageResponseChannelDto: components["schemas"]["PageResponse"] & {
            /** @description Paginated list of channels. */
            content?: components["schemas"]["ChannelDto"][];
        };
        PageResponseMemoryDto: components["schemas"]["PageResponse"] & {
            /** @description Paginated list of memories. */
            content?: components["schemas"]["MemoryDto"][];
        };
        PageResponseParticipantDto: components["schemas"]["PageResponse"] & {
            /** @description Paginated list of participants. */
            content?: components["schemas"]["ParticipantDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listChannels: {
        parameters: {
            query?: {
                /** @description Filter by direct message status. Omit to return all channels. */
                dm?: true | false;
                /** @description Case-insensitive substring filter on channel name or key. */
                query?: string;
                /** @description Page number (0-indexed). */
                page?: number;
                /** @description Number of items per page. */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of channels. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "content": [
                     *         {
                     *           "id": 1,
                     *           "channelKey": "#ncbot",
                     *           "channelName": "#ncbot",
                     *           "isDm": false,
                     *           "lastMessageAt": "2026-06-03T14:30:00Z"
                     *         },
                     *         {
                     *           "id": 2,
                     *           "channelKey": "#general",
                     *           "channelName": "#general",
                     *           "isDm": false,
                     *           "lastMessageAt": "2026-06-02T10:00:00Z"
                     *         },
                     *         {
                     *           "id": 3,
                     *           "channelKey": "d41d8cd98f00b204e9800998ecf8427e",
                     *           "channelName": null,
                     *           "isDm": true,
                     *           "lastMessageAt": null
                     *         }
                     *       ],
                     *       "totalPages": 1,
                     *       "currentPage": 0,
                     *       "totalElements": 3
                     *     }
                     */
                    "application/json": components["schemas"]["PageResponseChannelDto"];
                };
            };
            /** @description Invalid query parameter (e.g., non-integer `page`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric ID of the channel to delete. */
                channelId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channel deleted successfully. All associated messages and channel memories are also removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Channel not found. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getChannelMessages: {
        parameters: {
            query?: {
                /**
                 * @description Only return messages created before this instant (exclusive).
                 *     ISO-8601 format, e.g. `2026-06-03T12:00:00Z`.
                 */
                before?: string;
                /**
                 * @description Only return messages created after this instant (exclusive).
                 *     ISO-8601 format, e.g. `2026-06-03T08:00:00Z`.
                 */
                after?: string;
                /** @description Page number (0-indexed). */
                page?: number;
                /** @description Number of items per page. */
                size?: number;
                /** @description Sort order for the `createdAt` field. */
                sortDirection?: "ASC" | "DESC";
            };
            header?: never;
            path: {
                /** @description Numeric ID of the channel. */
                channelId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated message list for the channel. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "channelId": 1,
                     *       "channelName": "#ncbot",
                     *       "messages": [
                     *         {
                     *           "id": 101,
                     *           "senderName": "alice",
                     *           "content": "Hello everyone!",
                     *           "createdAt": "2026-06-03T14:30:00Z"
                     *         },
                     *         {
                     *           "id": 100,
                     *           "senderName": "bob",
                     *           "content": "Hey alice, how's it going?",
                     *           "createdAt": "2026-06-03T14:29:00Z"
                     *         }
                     *       ],
                     *       "totalPages": 5,
                     *       "currentPage": 0,
                     *       "totalElements": 97
                     *     }
                     */
                    "application/json": components["schemas"]["MessagesResponse"];
                };
            };
            /** @description Invalid query parameter or `channelId` not found. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getChannelMemory: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring filter on memory key or value. */
                query?: string;
                /** @description Page number (0-indexed). */
                page?: number;
                /** @description Number of items per page. */
                size?: number;
            };
            header?: never;
            path: {
                /** @description Numeric ID of the channel. */
                channelId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of channel-scoped memories. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "content": [
                     *         {
                     *           "id": 10,
                     *           "channelId": 1,
                     *           "key": "user.alice",
                     *           "value": "Alice is a regular contributor who enjoys discussing technology."
                     *         },
                     *         {
                     *           "id": 11,
                     *           "channelId": 1,
                     *           "key": "channel.topic",
                     *           "value": "#ncbot focuses on bot development and deployment."
                     *         }
                     *       ],
                     *       "totalPages": 1,
                     *       "currentPage": 0,
                     *       "totalElements": 2
                     *     }
                     */
                    "application/json": components["schemas"]["PageResponseMemoryDto"];
                };
            };
            /** @description Invalid query parameter or `channelId` not found. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createChannelMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric ID of the channel. */
                channelId: number;
            };
            cookie?: never;
        };
        /** @description The key-value pair for the new memory. */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "key": "user.bob",
                 *       "value": "Bob recently joined the channel and is learning the ropes."
                 *     }
                 */
                "application/json": components["schemas"]["MemoryCreateRequest"];
            };
        };
        responses: {
            /** @description Memory created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 42,
                     *       "channelId": 1,
                     *       "key": "user.bob",
                     *       "value": "Bob recently joined the channel and is learning the ropes."
                     *     }
                     */
                    "application/json": components["schemas"]["MemoryDto"];
                };
            };
            /** @description Invalid request body or `channelId` not found. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateChannelMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric ID of the channel. */
                channelId: number;
                /** @description Numeric ID of the memory to update. */
                id: number;
            };
            cookie?: never;
        };
        /** @description Updated key-value pair. */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "key": "user.bob",
                 *       "value": "Bob is now an active member and contributes regularly."
                 *     }
                 */
                "application/json": components["schemas"]["MemoryUpdateRequest"];
            };
        };
        responses: {
            /** @description Memory updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 42,
                     *       "channelId": 1,
                     *       "key": "user.bob",
                     *       "value": "Bob is now an active member and contributes regularly."
                     *     }
                     */
                    "application/json": components["schemas"]["MemoryDto"];
                };
            };
            /** @description Memory not found or memory does not belong to the specified channel. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteChannelMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric ID of the channel. */
                channelId: number;
                /** @description Numeric ID of the memory to delete. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory deleted successfully. No content returned. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Memory not found or memory does not belong to the specified channel. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    promoteMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric ID of the source channel. */
                channelId: number;
                /** @description Numeric ID of the memory to promote. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory promoted to global scope. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 99,
                     *       "channelId": null,
                     *       "key": "user.bob",
                     *       "value": "Bob is now an active member and contributes regularly."
                     *     }
                     */
                    "application/json": components["schemas"]["MemoryDto"];
                };
            };
            /** @description Memory not found or memory does not belong to the specified channel. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getChannelParticipants: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring filter on participant name. */
                query?: string;
                /** @description Page number (0-indexed). */
                page?: number;
                /** @description Number of items per page. */
                size?: number;
            };
            header?: never;
            path: {
                /** @description Numeric ID of the channel. */
                channelId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of channel participants. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "content": [
                     *         {
                     *           "id": 1,
                     *           "name": "alice",
                     *           "firstSeen": "2026-06-01T09:00:00Z",
                     *           "lastSeen": null,
                     *           "pathUpgradeNotifiedAt": "2026-06-02T10:00:00Z",
                     *           "blocked": false
                     *         },
                     *         {
                     *           "id": 2,
                     *           "name": "bob",
                     *           "firstSeen": "2026-06-01T10:00:00Z",
                     *           "lastSeen": null,
                     *           "pathUpgradeNotifiedAt": null,
                     *           "blocked": false
                     *         },
                     *         {
                     *           "id": 3,
                     *           "name": "charlie",
                     *           "firstSeen": "2026-06-01T11:00:00Z",
                     *           "lastSeen": null,
                     *           "pathUpgradeNotifiedAt": null,
                     *           "blocked": true
                     *         }
                     *       ],
                     *       "totalPages": 1,
                     *       "currentPage": 0,
                     *       "totalElements": 3
                     *     }
                     */
                    "application/json": components["schemas"]["PageResponseParticipantDto"];
                };
            };
            /** @description Invalid query parameter or `channelId` not found. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGlobalMemory: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring filter on memory key or value. */
                query?: string;
                /** @description Page number (0-indexed). */
                page?: number;
                /** @description Number of items per page. */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of global memories. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "content": [
                     *         {
                     *           "id": 5,
                     *           "channelId": null,
                     *           "key": "bot.version",
                     *           "value": "Running ncbot v2.3.1 with llama.cpp backend."
                     *         },
                     *         {
                     *           "id": 6,
                     *           "channelId": null,
                     *           "key": "channel.#ncbot",
                     *           "value": "#ncbot is the primary development channel for bot discussions."
                     *         }
                     *       ],
                     *       "totalPages": 1,
                     *       "currentPage": 0,
                     *       "totalElements": 2
                     *     }
                     */
                    "application/json": components["schemas"]["PageResponseMemoryDto"];
                };
            };
            /** @description Invalid query parameter. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createGlobalMemory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The key-value pair for the new global memory. */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "key": "bot.version",
                 *       "value": "Running ncbot v2.3.1 with llama.cpp backend."
                 *     }
                 */
                "application/json": components["schemas"]["MemoryCreateRequest"];
            };
        };
        responses: {
            /** @description Global memory created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 99,
                     *       "channelId": null,
                     *       "key": "bot.version",
                     *       "value": "Running ncbot v2.3.1 with llama.cpp backend."
                     *     }
                     */
                    "application/json": components["schemas"]["MemoryDto"];
                };
            };
            /** @description Invalid request body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateGlobalMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric ID of the memory to update. */
                id: number;
            };
            cookie?: never;
        };
        /** @description Updated key-value pair. */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "key": "bot.version",
                 *       "value": "Running ncbot v2.4.0 with ollama backend."
                 *     }
                 */
                "application/json": components["schemas"]["MemoryUpdateRequest"];
            };
        };
        responses: {
            /** @description Global memory updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 99,
                     *       "channelId": null,
                     *       "key": "bot.version",
                     *       "value": "Running ncbot v2.4.0 with ollama backend."
                     *     }
                     */
                    "application/json": components["schemas"]["MemoryDto"];
                };
            };
            /** @description Memory not found or memory is not global (belongs to a channel). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteGlobalMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric ID of the memory to delete. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Global memory deleted successfully. No content returned. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Memory not found or memory is not global (belongs to a channel). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All configuration items with metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigItemDto"][];
                };
            };
        };
    };
    updateConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Dot-namespaced configuration key (e.g. `bot.name`). */
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigItemUpdateRequest"];
            };
        };
        responses: {
            /** @description The updated configuration item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigItemDto"];
                };
            };
            /** @description Unknown key or value fails validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resetConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Dot-namespaced configuration key (e.g. `bot.name`). */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The configuration item now uses its default value. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigItemDto"];
                };
            };
            /** @description Unknown configuration item. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAllParticipants: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring filter on participant name. */
                query?: string;
                /** @description Page number (0-indexed). */
                page?: number;
                /** @description Number of items per page. */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of all participants with last seen timestamps. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "content": [
                     *         {
                     *           "id": 1,
                     *           "name": "alice",
                     *           "firstSeen": "2026-06-01T09:00:00Z",
                     *           "lastSeen": "2026-06-03T14:30:00Z",
                     *           "pathUpgradeNotifiedAt": "2026-06-02T10:00:00Z",
                     *           "blocked": false
                     *         },
                     *         {
                     *           "id": 2,
                     *           "name": "bob",
                     *           "firstSeen": "2026-06-01T10:00:00Z",
                     *           "lastSeen": "2026-06-03T14:29:00Z",
                     *           "pathUpgradeNotifiedAt": null,
                     *           "blocked": false
                     *         },
                     *         {
                     *           "id": 3,
                     *           "name": "charlie",
                     *           "firstSeen": "2026-06-01T11:00:00Z",
                     *           "lastSeen": "2026-06-03T12:00:00Z",
                     *           "pathUpgradeNotifiedAt": null,
                     *           "blocked": true
                     *         }
                     *       ],
                     *       "totalPages": 1,
                     *       "currentPage": 0,
                     *       "totalElements": 3
                     *     }
                     */
                    "application/json": components["schemas"]["PageResponseParticipantDto"];
                };
            };
            /** @description Invalid query parameter. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric ID of the participant to update. */
                participantId: number;
            };
            cookie?: never;
        };
        /** @description The new block state. */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "blocked": true
                 *     }
                 */
                "application/json": components["schemas"]["ParticipantUpdateRequest"];
            };
        };
        responses: {
            /** @description Participant updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1,
                     *       "name": "alice",
                     *       "firstSeen": "2026-06-01T09:00:00Z",
                     *       "lastSeen": "2026-06-03T14:30:00Z",
                     *       "pathUpgradeNotifiedAt": "2026-06-02T10:00:00Z",
                     *       "blocked": true
                     *     }
                     */
                    "application/json": components["schemas"]["ParticipantDto"];
                };
            };
            /** @description Participant not found or invalid request body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
